class BaseException(Exception):
    def getReturnObject(self):
        pass
